const books = [
  {
    id: 1,
    name: "THINK AND GROW RICH",
    author: "NAPOLEON HILL",
    year: 1937,
    namePublish: "Hawthorn, TarcherPerigee, Plume",
    numPage: 264,
    numCopy: 9,
  },
  {
    id: 2,
    name: "WHIPPED BY THE WIND",
    author: "MARGARET MITCHELL",
    year: 1936,
    namePublish: "Macmillan Publishers (United States)",
    numPage: 1037,
    numCopy: 3,
  },
  {
    id: 3,
    name: "TWILIGHT",
    author: "STEPHENIE MAYER",
    year: 2005,
    namePublish: "Little, Brown and Company",
    numPage: 498,
    numCopy: 11,
  },
  {
    id: 4,
    name: "THE ALCHEMIST",
    author: "PAULO COELHO",
    year: 1988,
    namePublish: "Portuguese",
    numPage: 163,
    numCopy: 4,
  },
  {
    id: 5,
    name: "THE DIARY OF ANNE FRANK",
    author: "ANNE FRANK",
    year: 1947,
    namePublish: "Contact Publishing",
    numPage: 283,
    numCopy: 1,
  },
  {
    id: 6,
    name: "THE DA VINCI CODE",
    author: "DAN BROWN",
    year: 2003,
    namePublish: "Doubleday",
    numPage: 689,
    numCopy: 13,
  },
  {
    id: 7,
    name: "LORD OF THE RINGS",
    author: "J. R. R. Tolkien",
    year: 1954,
    namePublish: "Allen & Unwin",
    numPage: 1191,
    numCopy: 5,
  },
  {
    id: 8,
    name: "HARRY POTTER",
    author: "JOHN ROWLING",
    year: 1997,
    namePublish: "Bloomsbury",
    numPage: 3407,
    numCopy: 19,
  },
  {
    id: 9,
    name: "QUOTATIONS FROM THE WORKS OF MAO ZEDUNG",
    author: "MAO ZEDUNG",
    year: 1964,
    namePublish: "People's Press",
    numPage: 427,
    numCopy: 5,
  },
  {
    id: 10,
    name: "THE GREAT GATSBY",
    author: "F.S. FITZGERALD",
    year: 1925,
    namePublish: "Charles Scribner's Sons",
    numPage: 208,
    numCopy: 2,
  },
];

const visitors = [
  {
    id: 1,
    name: "Mark Jackson",
    phone: "0679652158",
  },
  {
    id: 2,
    name: "Vicente Perez",
    phone: "0635684147",
  },
  {
    id: 3,
    name: "Nestor Evans",
    phone: "0698242328",
  },
  {
    id: 4,
    name: "Jax Howard",
    phone: "0615426558",
  },
  {
    id: 5,
    name: "Nathan Campbell",
    phone: "0636264765",
  },
  {
    id: 6,
    name: "Juliana Perry",
    phone: "0845165651",
  },
  {
    id: 7,
    name: "Camila Griffin",
    phone: "0168417761",
  },
  {
    id: 8,
    name: "Farida Anderson",
    phone: "0945131211",
  },
  {
    id: 9,
    name: "Frida Perez",
    phone: "0621985154",
  },
  {
    id: 10,
    name: "Zuri Murphy",
    phone: "0641512145",
  },
];


const cards = [
  {
    id: 1,
    visitor: "Mark Jackson",
    book: "THINK AND GROW RICH",
    borrDate: new Date().toLocaleDateString(),
    retDate: false,
  },
  {
    id: 2,
    visitor: "Mark Jackson",
    book: "WHIPPED BY THE WIND",
    borrDate: new Date("09.25.2023").toLocaleDateString(),
    retDate: new Date().toLocaleDateString(),
  },
  {
    id: 3,
    visitor: "Vicente Perez",
    book: "TWILIGHT",
    borrDate: new Date("08.21.2023").toLocaleDateString(),
    retDate: new Date("09.17.2023").toLocaleDateString(),
  },
  {
    id: 4,
    visitor: "Nestor Evans",
    book: "THE ALCHEMIST",
    borrDate: new Date("10.01.2023").toLocaleDateString(),
    retDate: false,
  },
  {
    id: 5,
    visitor: "Jax Howard",
    book: "THE DIARY OF ANNE FRANK",
    borrDate: new Date("09.01.2023").toLocaleDateString(),
    retDate: new Date("10.07.2023").toLocaleDateString(),
  },
  {
    id: 6,
    visitor: "Nathan Campbell",
    book: "THE DA VINCI CODE",
    borrDate: new Date("10.07.2023").toLocaleDateString(),
    retDate: false,
  },
  {
    id: 7,
    book: "LORD OF THE RINGS",
    visitor: "Juliana Perry",
    borrDate: new Date("05.05.2023").toLocaleDateString(),
    retDate: new Date("05.20.2023").toLocaleDateString(),
  },
  {
    id: 8,
    book: "HARRY POTTER",
    visitor: "Juliana Perry",
    borrDate: new Date("05.05.2023").toLocaleDateString(),
    retDate: false,
  },
  {
    id: 9,
    book: "QUOTATIONS FROM THE WORKS OF MAO ZEDUNG",
    visitor: "Camila Griffin",
    borrDate: new Date("07.05.2023").toLocaleDateString(),
    retDate: new Date("08.05.2023").toLocaleDateString(),
  },
  {
    id: 10,
    book: "THE GREAT GATSBY",
    visitor: "Farida Anderson",
    borrDate: new Date("07.05.2023").toLocaleDateString(),
    retDate: new Date("08.09.2023").toLocaleDateString(),
  },
  {
    id: 11,
    book: "THE GREAT GATSBY",
    visitor: "Frida Perez",
    borrDate: new Date("07.23.2023").toLocaleDateString(),
    retDate: new Date("10.05.2023").toLocaleDateString(),
  },
  {
    id: 12,
    book: "THE GREAT GATSBY",
    visitor: "Zuri Murphy",
    borrDate: new Date("08.19.2023").toLocaleDateString(),
    retDate: new Date("09.17.2023").toLocaleDateString(),
  },
];


export { books, visitors, cards };
